#!/usr/bin/env bash
# GreenNode notebook bootstrap: persistent layout, tmux, basics.
# Safe to re-run any time (and MUST be re-run after every instance Stop,
# because the block storage — including apt packages — is wiped).
#
# Usage (in a notebook terminal):   bash 00_bootstrap.sh
cd "$(dirname "$0")" || exit 1
# shellcheck source=lib.sh
. ./lib.sh

log "bootstrap: GPU = $(gpu_check)"
layout
log "layout ready under $NB_DATA"

ensure_tmux
log "tmux: $(command -v tmux || echo "$NB_DATA/bin/tmux")"

apt_try git git-lfs ffmpeg 2>/dev/null \
    || log "apt unavailable — relying on image-provided git/ffmpeg \
($(command -v git || echo 'git MISSING') $(command -v ffmpeg || echo 'ffmpeg MISSING'))"

# Persist a login snippet so new terminals get the same environment.
cat > "$NB_DATA/env.sh" <<EOF
# generated by 00_bootstrap.sh — source from any shell:  . $NB_DATA/env.sh
export NB_DATA="$NB_DATA"
export PIP_CACHE_DIR="\$NB_DATA/cache/pip"
export HF_HOME="\$NB_DATA/cache/huggingface"
export PATH="\$NB_DATA/bin:\$PATH"
EOF
grep -qs "notebook-data/env.sh" ~/.bashrc 2>/dev/null \
    || echo ". $NB_DATA/env.sh" >> ~/.bashrc || true

python3 - <<'EOF'
import shutil, sys
total, used, free = shutil.disk_usage("/")
print(f"[disk] block storage: {free / 1e9:.0f} GB free of {total / 1e9:.0f} GB")
sys.exit(0)
EOF

log "bootstrap done. Next: bash 10_gvhmr.sh, then bash 20_training.sh"
